# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dprint
        name: dprint
        types: [text]
        entry: dprint fmt --allow-no-files --fail-on-change
        # dprint uses concurrency when processing multiple files
        require_serial: true
        language: system

  - repo: local
    hooks:
      - id: tsc
        name: tsc
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
        entry: tsc --build --noEmit
        language: system
